### ISSUE TITLE
Question about ScanMapCB

### ISSUE THREAD

**Issue by WTIGER001** [ca110us/go-clamav#5]
Hello... Thanks for the project..

I am trying to scan data that is in memory (in a `[]byte`). I think that I am supposed to do the following, but I am unsure what "context interface{}" is meant to be

```
    fmap := clamav.OpenMemory(data)
   defer clamav.CloseMemory(fmap)

    virus, _, err := engine.ScanMapCB(fmap, "BYTEDATA", ???? )

```

**Comment by ca110us** [comment]
Here is the comment in `clamav.h`.
```c
 * @param context       An application-defined context struct, opaque to
 *                      libclamav. May be used within your callback functions.
```
If you don't need it, you can just pass the `nil`.

**Comment by WTIGER001** [comment]
Perfect.. Thanks.
